Added force to cold boot and more time to boot

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,7 +65,7 @@ jobs:
           echo "Listing available AVDs..."
           avdmanager list avd
           echo "Starting emulator..."
-          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-window -no-audio -gpu swiftshader_indirect -no-boot-anim -accel off &
+          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-window -no-audio -gpu swiftshader_indirect -no-boot-anim -no-snapshot-load -accel off &
 
 #      - name: Debug AVD List and Paths
 #        run: |
@@ -80,8 +80,8 @@ jobs:
       - name: Wait for Emulator to Boot
         run: |
           adb wait-for-device
-          adb shell input keyevent 82
-          sleep 60
+          sleep 100  # Allow emulator more time to boot
+          adb shell getprop sys.boot_completed | grep -m 1 '1' || (echo "Emulator failed to boot" && exit 1)
 
       # Install Node.js for Appium
       - name: Set Up Node.js
